services:
  node-red:
    image: 5minds/node-red:node-red-contrib-processcube-tools
    build:
      context: .
    ports:
      # node-red port
      - 1880:1880
      # debugger port
      - 9229:9229
    env_file:
      - .env
    environment:
      - TZ=Europe/Berlin
      # start node-red with debugger port open
      - NODE_OPTIONS=--inspect=0.0.0.0:9229
      #- NODE_OPTIONS=--inspect-brk=0.0.0.0:9229
    volumes:
      # required for mapping the current source into the directory
      - ./.:/package_src/
      # save the flows
      - ./.processcube/nodered:/data

